version: '3.8'
services:
  mysql_db:
    image: mariadb:10.2.32
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DataScience_root_2025
      MYSQL_DATABASE: DataScience_data
      MYSQL_USER: DataScience_user
      MYSQL_PASSWORD: DataScience_pass_2025
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pDataScience_root_2025"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: